odpi/egeria-connector-sas-viya

src/main/java/org/odpi/openmetadata/connector/sas/repository/connector/mapping/EntityMappingSASCatalog2OMRS.java
src/test/groovy/org/odpi/openmetadata/connector/sas/repository/connector/mapping/EntityMappingSASCatalog2OMRSTest.groovy

Update to fix locale issue with date comparisons.

fix: update for timestamp locale issue

---

.github/workflows/merge.yml
.github/workflows/release.yml

Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

Add missing environment to import secrets into workflow

---

.github/workflows/merge.yml
.github/workflows/release.yml
build.gradle

Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

Add docs on signing parms & fix swapped username/token for oss upload

---

.dockerignore
.github/workflows/merge.yml
Dockerfile

feat: adding docker file for building image

---

.dockerignore
.github/workflows/merge.yml
Dockerfile

fix for build-args invalid option

---

.github/workflows/merge.yml
build.gradle

Update the version information to 2.11 in all files.

chore: update version to 2.11-SNAPSHOT

---

Dockerfile
deployment.yaml

I will add instructions for the Kubernetes deployment soon after. I need the changes to the Dockerfile to ensure everything is working properly in Kubernetes.

Add Kubenetes deployment and update Dockerfile for TLS

---

deployment/kubernetes/README.md
deployment/kubernetes/configure.sh
deployment/kubernetes/deployment.yaml

Add instructions and a configuration script for deploying to a Kubernetes SAS Viya cluster

Add documentation for deploying to Kubernetes

---

.github/workflows/merge.yml
.github/workflows/release.yml
.github/workflows/verify.yml
build.gradle

Update version to 3.0-SNAPSHOT

---

.github/workflows/merge.yml
build.gradle

- updates version to 2.11 
- refines dependencies for test

(Release 2.11) Update version to 2.11

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>
* updates gradle to 7.1.1
* Fixes publishing for release

Update gradle to 7.1.1 and fix publishing for release

---

.github/workflows/merge.yml
build.gradle
deployment/kubernetes/deployment.yaml

chore: update to version 3.1-SNAPSHOT

---

.github/workflows/merge.yml
build.gradle

Update for dependencies and version number to match Egeria and get successful build.

chore: Update dependencies and version

---

.github/workflows/merge.yml
build.gradle

chore: update to match latest egeria version 3.3-SNAPSHOT

---

.github/workflows/merge.yml
build.gradle

#58 update for release 3.3

---

.github/workflows/merge.yml

Adding in platforms for docker builds.

#67 update for docker on ARM64

---

.github/workflows/merge.yml
build.gradle

#71 Update for new Version to 3.5-SNAPSHOT

---

.github/workflows/merge.yml
build.gradle

#70 update for release 3.4

---

README.md
src/main/java/org/odpi/openmetadata/connector/sas/client/SASCatalogRestClient.java
src/main/java/org/odpi/openmetadata/connector/sas/repository/connector/MetadataCollection.java
src/main/java/org/odpi/openmetadata/connector/sas/repository/connector/mapping/SASCatalogObject.java
src/main/resources/TypeDefMappings.json

Maps the Report type as well as the relationship between a report and its data sources.
Also adds support for mapping references in Catalog.

Add report/reference mapping

---

src/main/java/org/odpi/openmetadata/connector/sas/repository/connector/mapping/RelationshipMapping.java
src/main/resources/TypeDefMappings.json

Maps Data Models (and their relationships) from Catalog into Egeria.

Add model mapping

---

src/main/resources/TypeDefMappings.json

Maps SAS Data Plans into Egeria Processes

Map Data Plans

---

src/test/groovy/org/odpi/openmetadata/connector/sas/repository/connector/mapping/EntityMappingSASCatalog2OMRSTest.groovy
src/test/groovy/org/odpi/openmetadata/connector/sas/repository/connector/mapping/SASCatalogObjectTest.groovy

Add a few unit tests for new mapping functionality, and fix old tests that were failing

Add and fix unit tests

---

deployment/kubernetes/configure.sh
src/main/java/org/odpi/openmetadata/connector/sas/repository/connector/MetadataCollection.java

Fixes the string comparison and shebang line issues raised in this scan: https://lift.sonatype.com/results/github.com/odpi/egeria-connector-sas-viya/01FPT9SJCBEVHZ90H0A1JW754Q

Fix string comparison and add shebang line

---

out/production/resources/TypeDefMappings.json

Add decision mapping

---

.github/workflows/merge.yml
build.gradle

#88 Update for Egeria 3.6-SNAPSHOT

---

src/main/java/org/odpi/openmetadata/connector/sas/client/SASCatalogRestClient.java
src/main/resources/TypeDefMappings.json

Add associated relationship mapping to LineageMapping.
Also fix NullPointer when the "type" field on a relationship is not present.
Signed-off-by: Steven Green <steven.greens10@gmail.com>

Add associated relationship and fix nullpointer

---

.github/workflows/merge.yml
build.gradle

closes #90 
- formatting update for whitespace issues.

#90 update for release 3.5

---

.github/workflows/merge.yml
build.gradle

#106 Update for Egeria 3.7-SNAPSHOT

---

src/main/resources/TypeDefMappings.json

Signed-off-by: Steven Green <steven.greens10@gmail.com>

Add SAS Studio dataflow mapping

---

src/main/resources/TypeDefMappings.json

Signed-off-by: Steven Green <steven.greens10@gmail.com>

Add Model Manager project mapping

---

.github/workflows/merge.yml
build.gradle

chore: #115 Update for Egeria 3.8-SNAPSHOT

---

src/main/java/org/odpi/openmetadata/connector/sas/client/SASCatalogRestClient.java
src/main/java/org/odpi/openmetadata/connector/sas/repository/connector/mapping/AttributeMapping.java
src/main/resources/TypeDefMappings.json

Signed-off-by: Steven Green <steven.greens10@gmail.com>

Add file mapping and fix up some attributes

---

deployment/kubernetes/deployment.yaml
src/main/resources/TypeDefMappings.json

Ingress objects now require 'ingressClassName'

Make SQL mapping consistent and fix Kubernetes ingress

---

.github/workflows/merge.yml
build.gradle

#114 update for release 3.10

---

.github/workflows/merge.yml
build.gradle

chore: #150 update for Egeria 3.12-SNAPSHOT

---

CONTRIBUTING.md
README.md
src/main/java/org/odpi/openmetadata/connector/sas/repository/connector/stores/TypeDefStore.java

Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>
Further updates for master->main rename
See #6907 
@CDaRip2U These are the updates are found as a consequence of our master->main renaming

odpi/egeria#6907 further updates master->main
